"use client";

import { useState } from "react";

/**
 * AffiliateDisclosure component displays FTC-compliant affiliate disclosure
 * Can be shown as a banner or modal
 */
export default function AffiliateDisclosure() {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      {/* Modal */}
      {isOpen && (
        <div
          className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4"
          onClick={() => setIsOpen(false)}
        >
          <div
            className="bg-white rounded-lg max-w-2xl w-full max-h-[80vh] overflow-y-auto p-6"
            onClick={(e) => e.stopPropagation()}
          >
            <div className="flex justify-between items-start mb-4">
              <h2 className="text-2xl font-bold text-gray-900">Affiliate Disclosure</h2>
              <button
                onClick={() => setIsOpen(false)}
                className="text-gray-400 hover:text-gray-600 text-2xl"
              >
                ×
              </button>
            </div>

            <div className="space-y-4 text-gray-700">
              <p>
                <strong>SwiftHerb participates in affiliate marketing programs.</strong>
              </p>
              
              <p>
                When you click on product links on our website and make purchases on iHerb.com, 
                we may earn a commission at no additional cost to you. This helps support our 
                service and allows us to provide free AI-powered supplement recommendations.
              </p>

              <p>
                <strong>How it works:</strong>
              </p>
              <ul className="list-disc pl-6 space-y-1">
                <li>We recommend products based on your health queries</li>
                <li>When you click a product link, you&apos;re redirected to iHerb.com</li>
                <li>If you make a purchase, we earn a small commission</li>
                <li>You pay the same price - no additional cost to you</li>
              </ul>

              <p>
                <strong>Our commitment:</strong> We only recommend products that we believe 
                may be helpful based on your queries. Our recommendations are generated by 
                AI analysis and are not influenced by commission rates.
              </p>

              <div className="mt-4 p-4 bg-red-50 border border-red-200 rounded-lg">
                <p className="font-semibold text-red-800 mb-2">
                  ⚠️ Important Medical Disclaimer:
                </p>
                <p className="text-sm text-red-700">
                  SwiftHerb is <strong>NOT</strong> a medical service and does <strong>NOT</strong> provide medical advice. 
                  The information provided is for educational purposes only and should not replace professional medical advice, 
                  diagnosis, or treatment. Always consult with a qualified healthcare provider before starting any supplement regimen, 
                  especially if you have a medical condition, are taking medications, are pregnant, or are nursing.
                </p>
              </div>

              <p className="text-sm text-gray-600 mt-4">
                This disclosure is provided in compliance with FTC guidelines for affiliate marketing.
              </p>

              <div className="pt-4 border-t">
                <button
                  onClick={() => setIsOpen(false)}
                  className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
                >
                  I Understand
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
