#!/usr/bin/env node
/**
 * Generate public/_redirects (Cloudflare Pages) from content/admitad-landings.json:
 * one first-party redirect per partner program, /go/<slug> → tracking link (302).
 *
 * Why: ad blockers cosmetic-filter anchors whose href matches known affiliate
 * domains (tatrck.com). Pointing CTAs at our own /go/ path and letting the CDN
 * issue the redirect keeps buttons visible and clicks working — no client JS.
 *
 * Both slash forms are emitted because the site uses trailingSlash: true.
 * Cloudflare Pages allows up to 2,000 static redirects; we're well under.
 *
 * Usage: pnpm partners:redirects  (also part of pnpm partners:sync)
 */
const fs = require('fs');
const path = require('path');

const DATA_FILE = path.join(__dirname, '..', 'content', 'admitad-landings.json');
const OUTPUT = path.join(__dirname, '..', 'public', '_redirects');

const payload = JSON.parse(fs.readFileSync(DATA_FILE, 'utf8'));
const entries = (payload.entries || []).filter((e) => e?.admitad?.gotolink && e?.slug);

const lines = [
  '# Generated by pnpm partners:redirects — do not edit by hand.',
  '# First-party affiliate redirects: /go/<slug> -> partner tracking link.',
];
for (const e of entries) {
  lines.push(`/go/${e.slug} ${e.admitad.gotolink} 302`);
  lines.push(`/go/${e.slug}/ ${e.admitad.gotolink} 302`);
}

fs.writeFileSync(OUTPUT, `${lines.join('\n')}\n`, 'utf8');
console.log(`[redirects] wrote ${entries.length} programs (${lines.length - 2} rules) to ${path.relative(process.cwd(), OUTPUT)}`);
if (entries.length * 2 > 1800) {
  console.warn('[redirects] WARNING: approaching the 2,000-rule Cloudflare Pages limit.');
}
