name = "swiftherb-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

# KV Namespace binding
[[kv_namespaces]]
binding = "PRODUCTS"
id = "cc09538377c34c08916ac38a0f5846ed"

# Environment variables
[vars]
ENVIRONMENT = "production"

# For local development
[dev]
port = 8787
local_protocol = "http"
